<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  server01:
    roles:
      - server
      - default
      - registry
      - el7
      - docker
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
  server02:
    roles:
      - el7
      - docker
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
  server03:
    roles:
      - el7
      - docker
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 512
  synced_folder: disabled
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
# vb_gui: true
